# Generated by Django 6.0 on 2025-12-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVerdict',
            fields=[
                ('post_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('verdict', models.IntegerField()),
            ],
            options={
                'db_table': 'post_verdict',
                'managed': False,
            },
        ),
    ]
