# Generated by Django 5.1.7 on 2025-12-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_postverdict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('time_stamp', models.TimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'chats',
                'managed': False,
            },
        ),
    ]
