# Generated by Django 5.1.7 on 2025-12-20 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_chats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=10)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='database.posts')),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.DeleteModel(
            name='Chats',
        ),
    ]
