# Generated by Django 5.1.7 on 2025-12-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_chat_delete_chats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Chats',
        ),
    ]
